language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: python -m unittest discover -s src/tests -t .
notifications:
  email:
    on_failure: always
    on_success: change