language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: cd project/src/ && python -m unittest discover games/
notifications:
  email:
    on_failure: always
    on_success: change