#!/usr/bin/env python
# For controlling the daemon that displays games.
import main
import sys

# Usage of this command.
USAGE = "Usage: daemon_ctl {start|stop|restart}"

# Create a daemon control object.
daemon = main.CubbieBoardDaemon('/tmp/cubbie-board.pid', stdout='debug/stdout.txt', stderr='debug/stderr.txt')

# If 1 arg, process it.
if len(sys.argv) == 2:
    if sys.argv[1] == 'start':
        daemon.start()
    elif sys.argv[1] == 'stop':
        daemon.stop()
    elif sys.argv[1] == 'restart':
        daemon.restart()
    else:
        print('Invalid argument')
else:
    print(USAGE)
